##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := mainPinTool

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := stexposer

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=


###### Define the sanity subset ######

# This defines the list of tests that should run in sanity. It should include all the tests listed in
# TEST_TOOL_ROOTS and TEST_ROOTS excluding only unstable tests.
SANITY_SUBSET := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)


##############################################################
#
# Test recipes
#
##############################################################

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.


# Build the intermediate object file.
$(OBJDIR)mainPinTool$(OBJ_SUFFIX): mainPinTool.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $<

#add the two following lines for any new couple (.h and .cpp) i will need to include
$(OBJDIR)g_instrumentation$(OBJ_SUFFIX): g_instrumentation.cpp g_instrumentation.h
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)g_actions$(OBJ_SUFFIX): g_actions.cpp g_actions.h
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)g_stages$(OBJ_SUFFIX): g_stagestypes.cpp g_stagestypes.h
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<
	
$(OBJDIR)g_stateexposer$(OBJ_SUFFIX): stateExposer.cpp stateExposer.h
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<
# Build the tool as a dll (shared object).
$(OBJDIR)mainPinTool$(PINTOOL_SUFFIX): $(OBJDIR)mainPinTool$(OBJ_SUFFIX) $(OBJDIR)g_instrumentation$(OBJ_SUFFIX) g_instrumentation.h $(OBJDIR)g_actions$(OBJ_SUFFIX) g_actions.h $(OBJDIR)g_stages$(OBJ_SUFFIX) g_stagestypes.h $(OBJDIR)g_stateexposer$(OBJ_SUFFIX) stateExposer.h
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) $(LINK_EXE)$@ $(^:%.h=) $(TOOL_LPATHS) $(TOOL_LIBS)



#$(OBJDIR)mainPinTool$(OBJ_SUFFIX): mainPinTool.cpp
#	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $<

# Build the tool as a dll (shared object).
#$(OBJDIR)mainPinTool$(PINTOOL_SUFFIX): $(OBJDIR)mainPinTool$(OBJ_SUFFIX)
#	$(LINKER) $(TOOL_LDFLAGS_NOOPT) $(LINK_EXE)$@ $< $(TOOL_LPATHS) $(TOOL_LIBS)
