#PIN_ROOT_DIR = $(PIN_ROOT)
#CPPFLAGS = -I$(PIN_ROOT_DIR)
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
#include $(PIN_ROOT)/source/tools/ManualExamples/makefile.rules
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
